[project]
name = "Mastermind-Algoritmos-Geneticos"
version = "1.0.0"
description = "Algoritmo genético para resolver el juego Mastermind"
authors = [
    { name = "Miguel Bastos", email = "miguelbastosgandara11@gmail.com" }
]
dependencies = [
    "matplotlib>=3.10.1"
]
